// react-chat/src/App.jsx
import { useEffect } from "react";
import { useChatStore } from "./store/chatStore";
import ChatWindow from "./components/ChatWindow";

function App() {
  const initSocket = useChatStore((state) => state.initSocket);
  const cleanupSocket = useChatStore((state) => state.cleanupSocket);

  useEffect(() => {
    initSocket();
    return () => cleanupSocket();
  }, [initSocket, cleanupSocket]);

  return (
    <div className="max-w-xl mx-auto p-6 text-base-content">
      <ChatWindow />
    </div>
  );
}

export default App;

// vue-chat/src/App.vue
<script setup>
import { onMounted, onUnmounted } from "vue";
import { useChatStore } from "./stores/chatStore";
import ChatWindow from "./components/ChatWindow.vue";

const chat = useChatStore();

onMounted(() => {
  chat.initSocket();
});

onUnmounted(() => {
  chat.cleanupSocket();
});
</script>

<template>
  <div class="max-w-xl mx-auto p-6">
    <ChatWindow />
  </div>
</template>
