// react-chat/src/components/StatusIndicator.jsx
import { useChatStore } from "../store/chatStore";

function StatusIndicator() {
    const connected = useChatStore((state) => state.connected);
    return (
        <div className="flex items-center gap-2">
            <span className={`badge ${connected ? 'badge-success' : 'badge-error'} badge-sm`}></span>
            <span className="text-xs font-medium uppercase tracking-wider opacity-70">
                {connected ? 'En línea' : 'Desconectado'}
            </span>
        </div>
    )
}

export default StatusIndicator;

// vue-chat/src/components/StatusIndicator.vue
<script setup>
import { useChatStore } from "../stores/chatStore.js";
const chat = useChatStore();
</script>

<template>
  <div class="flex items-center gap-2">
    <span
      class="badge badge-sm"
      :class="chat.connected ? 'badge-success' : 'badge-error'"
    ></span>

    <span class="text-xs font-medium uppercase tracking-wider opacity-70">
      {{ chat.connected ? "En línea" : "Desconectado" }}
    </span>
  </div>
</template>
